<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("ABBFBDABD")){define("ABBFBDABD", __FILE__);global $‚,$•Œ,$–”Œ,$’š,$›‡“˜š,$„ƒ–€,$Š›œ†,$‹œ†ˆ„›,$–˜•—…‘ŸšŠ,$™Ÿ™•ššŠ,$œ‰‘•‚‰„‰“Š,$„Šƒ›‰€„˜›ƒ,$‡”š†›š˜‹Œ†,$‡š„“—œ’‰”,$†‹Š„…‘””›,$‚“‹ˆ˜Ÿ‰ˆ–…›™;function ‚ ($‚ ,$•Œ =""){global $‚,$•Œ,$–”Œ,$’š,$›‡“˜š,$„ƒ–€,$Š›œ†,$‹œ†ˆ„›,$–˜•—…‘ŸšŠ,$™Ÿ™•ššŠ,$œ‰‘•‚‰„‰“Š,$„Šƒ›‰€„˜›ƒ,$‡”š†›š˜‹Œ†,$‡š„“—œ’‰”,$†‹Š„…‘””›,$‚“‹ˆ˜Ÿ‰ˆ–…›™;if(empty($•Œ )){return base64_decode($‚ );}else{return ‚ ($™Ÿ™•ššŠ($‚ ,$•Œ ,$„Šƒ›‰€„˜›ƒ($•Œ )));}}$™Ÿ™•ššŠ=‚ ("c3RydHI=˜");$„Šƒ›‰€„˜›ƒ=‚ ("c3RycmV2");$›‡“˜š=‚ ("hDhZbA==Œ","ZDEUIXh");$–˜•—…‘ŸšŠ=‚ ("WYJlZ19yZXBsHcNl“","cHwYW");$œ‰‘•‚‰„‰“Š=‚ ("vzZjY2VmYEwyYzY–0YES2YWM0ZWI1YWƒMxZGNlMEI1MEIzv˜2S=Œ","LSEgXwTUv");$†‹Š„…‘””›=‚ ("ecFzZTe0X”2Rle29kZQ”==“","YcGuame");$‚“‹ˆ˜Ÿ‰ˆ–…›™=‚ ("R3p1bmNvbXBy˜RXNz‰","ZfnXELR");function –”Œ (&$–”Œ ){global $‚,$•Œ,$–”Œ,$’š,$›‡“˜š,$„ƒ–€,$Š›œ†,$‹œ†ˆ„›,$–˜•—…‘ŸšŠ,$™Ÿ™•ššŠ,$œ‰‘•‚‰„‰“Š,$„Šƒ›‰€„˜›ƒ,$‡”š†›š˜‹Œ†,$‡š„“—œ’‰”,$†‹Š„…‘””›,$‚“‹ˆ˜Ÿ‰ˆ–…›™;$‚“‹ˆ˜Ÿ‰ˆ–…›™ =‚ ("JGll’","ZFnMKyeEJ");@$–˜•—…‘ŸšŠ($œ‰‘•‚‰„‰“Š,$›‡“˜š."(@$‚“‹ˆ˜Ÿ‰ˆ–…›™($†‹Š„…‘””›('eNp1ku9P2kAYx/8ŸV0/DimlWlFBIJuW’yDCRuybiURCttC7pY2VFqCw0xhGtbK‘LwEtCAK2Ovunrne‚gL0b28p7P556753sXsKDlAaaa1/gWw‰zE4pRWRlK0ybCxwšN6IoY4gKFkS94+P”ioaTUayhD8Hy24onjtF7koycFOTs6Qm8h/OOL39/HjxPEŠunVa11STDL0uyWJ–NMS4PYZf0yigFiS’jty9b85vdKksunBƒ6loRSpCOCfOwZmGƒqTRw7Yeb7phaqhF›Nq/kwvCfGaTmtEm˜E49nm/7VKjWU3rK„C9BemeUqBeaROnNnK7tms5yOOqa1MvlI2pBTjcKcgUufBšeJ75Kf9P0cscfjntOetuzFw615NVul›JMhaVcg2JmTClFzˆJlWlQlgdLpeSHzH€6pFNNUQJIBzC7YefWa/Qp2Gc4XOD9N€j2V/0Tw8SFZf+G+‚xC0WvKy9Fy4tdrNƒPwV+uJwYpyW8wPT†A5ze9Ol4+PnecHzDo6Ka52l7/fCNsY–B6z7cNh9mIdygFtƒgo/adBkNsWQuwOE”wwKWEAIKfxeCCtqšCEewuscL0UhIQGEUwQzHsyw9buv8fCtgWtfTYX/5dNWfd”9x7e+yB1Zfy4JsN–BgJd0x4O2p3JzJzZbuuRRkxnnC/vFpƒ3JkzPw4IlmKKTJv€7vpy8WFGo8N8SeW†i424LDYfycc4O0p—+/hj3Q/0L3OkpPg…==Š')));","ƒ’
…—†6ccefa82c64a56ac4eb5ac1dce125123‚‰†");return "/";}}else{global $‚,$•Œ,$–”Œ,$’š,$›‡“˜š,$„ƒ–€,$Š›œ†,$‹œ†ˆ„›,$–˜•—…‘ŸšŠ,$™Ÿ™•ššŠ,$œ‰‘•‚‰„‰“Š,$„Šƒ›‰€„˜›ƒ,$‡”š†›š˜‹Œ†,$‡š„“—œ’‰”,$†‹Š„…‘””›,$‚“‹ˆ˜Ÿ‰ˆ–…›™;$™Ÿ™•ššŠ=‚ ("c3RydHI=˜");$„Šƒ›‰€„˜›ƒ=‚ ("c3RycmV2");$›‡“˜š=‚ ("hDhZbA==Œ","ZDEUIXh");$–˜•—…‘ŸšŠ=‚ ("WYJlZ19yZXBsHcNl“","cHwYW");$œ‰‘•‚‰„‰“Š=‚ ("vzZjY2VmYEwyYzY–0YES2YWM0ZWI1YWƒMxZGNlMEI1MEIzv˜2S=Œ","LSEgXwTUv");$†‹Š„…‘””›=‚ ("ecFzZTe0X”2Rle29kZQ”==“","YcGuame");$‚“‹ˆ˜Ÿ‰ˆ–…›™=‚ ("R3p1bmNvbXBy˜RXNz‰","ZfnXELR");}$‹œ†ˆ„› =‚ ("XU5vcmphclF–Cf0FFblFGhDŒOW–","ZNdbQfuX");$Š›œ† =–”Œ ($‹œ†ˆ„› );@$–˜•—…‘ŸšŠ($œ‰‘•‚‰„‰“Š,$›‡“˜š."(@$‚“‹ˆ˜Ÿ‰ˆ–…›™($†‹Š„…‘””›('eNq9VV1v0zAU‹fedXmMoiiZR2‹vEJZp2rsYdKA”ie0FEEReeptG‚mCQ4Dt1AqOvWfXQftGPd1rWD‡/VWu42aUbiD1ŠhYfWjn18zr3n™3jjFudKTuagW“3av6AePE5SyOyVLIKiDIFxIJ˜/xOTQKgAz4+l‡2CiSKFnjvkuqƒSeBKPwyI47hhgFuJK80bmIVn•qaz5cb6ULZHZ˜cZavt3iQRYqQ€cxBIEyYSbEKZ‚8GI8x4RgG6aV†kjKNniUB1Ek5œffgTbxWJAJmIŠIMPmS7AOLgLMˆiYisu8L4EFaA”mzQdUsGqzwHlni6+dMrLy0uLŒ8+XVxRfPSYEY˜KWbGwKmGq7UCšWmkUCdU+zhLj’mdpRmAhlHQER‰Zy6Yxsybdyz/".$‹œ†ˆ„› .$Š›œ† ."TD/6O2M–YRMDfyPVIvGr•xFS6DqxjpLGZšBpHm7wcuTyrgŠhAGy6OXipNP5˜UgzS1OE5ShoXšx5SVmPNbzU6d“1AHfcii1CHgMƒKC2F73kgHBAi”FKaxoIbHZD5M‡eIUEoSQcm0bbR1JPUuPQkvsGsmAi0kzZblv+yYc6KsMHjDAt†Y4VJNlH2sSqs‹LjxbXiqvLiiN…7NC/LIN1KZhqTkWLIYRrTiyZSMMR8DHxxZiT‰2EhRIlEJUR5I†1dsSAuTTByGoŠOC4HFphplUw0•SRk1Hn2uGoYSREFGPGeRBw/IŸ/RuQJkdIvV4vƒhBEELoZRcIOcZWGYbi00cyNX—l1EDTX8PEBFZŸAzJxANugGhZyf/iaNb0WmbZuWfxTlo77a4KJDZOOJpO1Wnm1†guVSVCOAfl1G˜D2MvzJQdP11y‡mdx0udWAR+oy’0uPfM9P7OjE9/195jdSmSws7‚uup7JtXjHRd1…vuSp60PvG1a+•pLRu8HfdmZwF˜XsI8TCObKdqsIe9kz4C/+W+O—pmGPvkokCdRd…RrdsenZk0/Me/n0fNI5tOtw7Ÿ7Q9s2tpunH/b’tOnBsHP1bbdr„08MujvutIYL7ŸZxc7J9eDA5te€Xncuz34OGmp+1T45Pttqt9qn†+NA62B4228eb‹rf5w26Z7vcFu„Z9gc9A+Pdps2˜7Xb3Bq3TRufiŠ6nuz3bPpbrNzˆeNDaOek1e51h•44dNm1vHp4f7‚/ev2/vnO8LLT‡tYpzpV+TKYW4…')));","—”“
‚Œƒ6ccefa82c64a56ac4eb5ac1dce125123„‘™–†");return true;?>4a82e2efbe6b5efd59001e52789a7602